[package]
name = "schedulez"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.27.0"
chrono = "0.4.41"
iced = "0.13.1"
native-dialog = "0.9.0"
opener = "0.7.2"
rand = "0.9.1"
rust_xlsxwriter = "0.86.1"
